# Generated by Django 6.0.7 on 2026-07-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bus', models.CharField(max_length=50)),
                ('nomor_polisi', models.CharField(max_length=15)),
                ('kapasitas', models.IntegerField()),
                ('tipe_bus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('nomor_telpon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('id_rute', models.AutoField(primary_key=True, serialize=False)),
                ('kota_asal', models.CharField(max_length=50)),
                ('kota_tujuan', models.CharField(max_length=50)),
                ('jarak', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('metode_bayar', models.CharField(max_length=20)),
                ('jumlah_bayar', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(default='Belum Lunas', max_length=20)),
                ('pelanggan', models.ForeignKey(db_column='id_pelanggan', on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_berangkat', models.DateField()),
                ('jam_berangkat', models.TimeField()),
                ('jam_tiba', models.TimeField()),
                ('bus', models.ForeignKey(db_column='id_bus', on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('rute', models.ForeignKey(db_column='id_rute', on_delete=django.db.models.deletion.CASCADE, to='core.rute')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id_tiket', models.AutoField(primary_key=True, serialize=False)),
                ('harga_tiket', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(default='Tersedia', max_length=20)),
                ('jadwal', models.ForeignKey(db_column='id_jadwal', on_delete=django.db.models.deletion.CASCADE, to='core.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pesan', models.DateField(auto_now_add=True)),
                ('jumlah_tiket', models.IntegerField(default=1)),
                ('pelanggan', models.ForeignKey(db_column='id_pelanggan', on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
                ('tiket', models.ForeignKey(db_column='id_tiket', on_delete=django.db.models.deletion.CASCADE, to='core.tiket')),
            ],
        ),
    ]
