# Generated by Django 5.2.13 on 2026-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bus_photos/'),
        ),
    ]
