# Generated by Django 5.2.13 on 2026-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
