# Generated by Django 5.2.13 on 2026-07-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pelanggan_email_pelanggan_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='bukti_bayar',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
