# Generated by Django 5.2.13 on 2026-07-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pembayaran_bukti_bayar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sopir',
            fields=[
                ('id_sopir', models.AutoField(primary_key=True, serialize=False)),
                ('nama_sopir', models.CharField(max_length=100)),
                ('nomor_lisensi', models.CharField(max_length=30)),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('status_tugas', models.CharField(default='Tersedia', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='bagasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='sopir',
            field=models.ForeignKey(blank=True, db_column='id_sopir', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sopir'),
        ),
    ]
