# Generated by Django 5.2.13 on 2026-07-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sopir_pemesanan_bagasi_jadwal_sopir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='sopir',
        ),
        migrations.AddField(
            model_name='bus',
            name='sopir',
            field=models.OneToOneField(blank=True, db_column='id_sopir', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sopir'),
        ),
    ]
