# Generated by Django 5.2.13 on 2026-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pemesanan_nomor_kursi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
