# Generated by Django 5.2.13 on 2026-07-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pembayaran_order_id_pembayaran_snap_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='metode_bayar',
            field=models.CharField(blank=True, default='Online', max_length=20, null=True),
        ),
    ]
