# Generated by Django 5.2.13 on 2026-07-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pembayaran_metode_bayar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='bukti_bayar',
        ),
    ]
