# Generated by Django 5.2.13 on 2026-07-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pembayaran_bukti_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
