# Generated by Django 5.2.13 on 2026-07-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pemesanan_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='layanan_bagasi',
            field=models.BooleanField(default=False),
        ),
    ]
