# Generated by Django 5.2.13 on 2026-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pemesanan_layanan_bagasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='status_hadir',
            field=models.CharField(default='Belum Hadir', max_length=20),
        ),
    ]
