# Generated by Django 5.2.13 on 2026-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pemesanan_status_hadir'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopir',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
